name: 'PagerDuty Alert'
description: 'GitHub Action to trigger/resolve a critical PagerDuty alert'
inputs:
  pagerduty-integration-key:
    description: 'The integration key for your PagerDuty service'
    required: true
  pagerduty-dedup-key:
    description: 'The key used to correlate PagerDuty triggers, acknowledges, and resolves for the same alert.'
    required: false
  trigger_action:
    description: 'The type of event. Can be trigger, acknowledge or resolve'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'alert-triangle'
  color: 'red'
